- name: Install required packages for Prometheus
  package:
    name: "{{ prometheus_dependencies }}"
    state: present
  when:
    - ansible_distribution in ['Debian', 'Ubuntu']
    - ansible_distribution in ['Amazon', 'Fedora', 'RedHat']
  

- name: Create user for Prometheus
  user:
    name: prometheus
    system: true
    shell: /usr/sbin/nologin
    createhome: false

- name: Creating Prometheus Data directories
  file:
    path: "{{ prom_data_dir }}"
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0755


- name: Creating Prometheus configuration directories
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0750  #check why this permission
  with_items:
    - "{{ prom_conf_dir}}"
    - "{{ prom_conf_dir}}/rules"
    - "{{ prom_conf_dir}}/templates"

- name: Download prometheus binary
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ __prometheus_checksum }}"


- name: Extract prometheus package
  unarchive:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz
    dest: /opt/
    remote_src: yes


- name: Move Prometheus directory to the final location
  file:
    src: /opt/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}
    dest: /opt/prometheus
    state: link
    force: yes


- name: Create a symlink to the prometheus binary
  file:
    src: /opt/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    state: link

- name: Create a symlink to the promtool binary
  file:
    src: /opt/prometheus/promtool
    dest: /usr/local/bin/promtool
    state: link


- name: Copy prometheus configuration file
  copy:
    src: /opt/prometheus/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  notify: 
    - Reload systemd 
    - Start prometheus_service 





